---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - "vars/apply.yml"
    - "defaults/main.yml"
  pre_tasks:
    - name: copy terraform files from templates
      copy: 
        src: "{{ item }}"
        dest: "."
      with_fileglob:
        - "*.tf"
        - "*.tfvars"
        - "*.conf"
        - "*.pub"

  roles:
    - role: terraform 

  post_tasks:
    - name: delete terraform files after execution
      shell: "rm *.tf *.tfvars *.conf *.pub"
